# Generated by Django 5.2.13 on 2026-04-10 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cin',
            field=models.CharField(blank=True, help_text="Carte d'Identité Nationale", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Fes', 'Fès'), ('Marrakech', 'Marrakech'), ('Tangier', 'Tanger'), ('Agadir', 'Agadir'), ('Meknes', 'Meknès'), ('Oujda', 'Oujda'), ('Other', 'Autre')], default='Casablanca', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+212600000000' ou '0600000000'.", regex='^(?:\\+212|0)[5-7]\\d{8}$')]),
        ),
    ]
