# Generated by Django 5.2.13 on 2026-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_cin_patient_city_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text="Nom et téléphone du contact d'urgence", max_length=150, null=True),
        ),
    ]
