# Generated by Django 5.2.14 on 2026-05-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
