# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTOR', 'Médecin'), ('SECRETARY', 'Secrétaire'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
