# Generated by Django 5.2.14 on 2026-05-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTOR', 'Médecin'), ('SECRETARY', 'Secrétaire')], default='SECRETARY', max_length=20),
        ),
    ]
