# Generated by Django 5.2.15 on 2026-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DOCTOR', 'Médecin'), ('SECRETARY', 'Secrétaire'), ('PATIENT', 'Patient')], default='SECRETARY', max_length=20),
        ),
    ]
