# Generated by Django 5.2.13 on 2026-04-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.TextField(help_text='Liste des médicaments')),
                ('dosage', models.TextField(help_text='Dosage pour chaque médicament')),
                ('posology', models.TextField(help_text='Posologie détaillée')),
                ('duration', models.CharField(help_text='Durée du traitement', max_length=100)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation')),
            ],
        ),
    ]
