# Generated by Django 5.2.13 on 2026-04-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField(help_text='Liste des symptômes séparés par des virgules')),
                ('clinical_examination', models.TextField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('ai_suggestions', models.JSONField(blank=True, help_text="{ 'predictions': [...] }", null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
            ],
        ),
    ]
