# Generated by Django 5.2.14 on 2026-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_whatsappsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='phone_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
